// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2bWtC2GDahfaXgINA9OGRxlfIa3QzUQM',
    appId: '1:12563388694:web:836d61739d12cdfbfd5837',
    messagingSenderId: '12563388694',
    projectId: 'coco-mobile-app-f0e69',
    authDomain: 'coco-mobile-app-f0e69.firebaseapp.com',
    storageBucket: 'coco-mobile-app-f0e69.firebasestorage.app',
    measurementId: 'G-CX3MKJ1KV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9lgQ1boXVxR_uAyizkPKdy_QEh2AHa0',
    appId: '1:12563388694:android:001b4e4dab782560fd5837',
    messagingSenderId: '12563388694',
    projectId: 'coco-mobile-app-f0e69',
    storageBucket: 'coco-mobile-app-f0e69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCspQOQbFGxpVsfpulIZONQiv3rrcyg_DE',
    appId: '1:12563388694:ios:988f4cdd8872a6bcfd5837',
    messagingSenderId: '12563388694',
    projectId: 'coco-mobile-app-f0e69',
    storageBucket: 'coco-mobile-app-f0e69.firebasestorage.app',
    iosBundleId: 'com.example.cocoMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCspQOQbFGxpVsfpulIZONQiv3rrcyg_DE',
    appId: '1:12563388694:ios:988f4cdd8872a6bcfd5837',
    messagingSenderId: '12563388694',
    projectId: 'coco-mobile-app-f0e69',
    storageBucket: 'coco-mobile-app-f0e69.firebasestorage.app',
    iosBundleId: 'com.example.cocoMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2bWtC2GDahfaXgINA9OGRxlfIa3QzUQM',
    appId: '1:12563388694:web:dc1e04b36d2bcd1cfd5837',
    messagingSenderId: '12563388694',
    projectId: 'coco-mobile-app-f0e69',
    authDomain: 'coco-mobile-app-f0e69.firebaseapp.com',
    storageBucket: 'coco-mobile-app-f0e69.firebasestorage.app',
    measurementId: 'G-R1EKH5WVZ1',
  );

}